update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,25 +22,25 @@ jobs:
       - name: Clean & Build (skip tests)
         run: mvn clean package -B -DskipTests --file pom.xml
 
-      - name: Build Docker Image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: Dockerfile
-          push: false
-          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-boot-for-beginners:latest
+      - name: Check Docker Hub username
+        run: |
+          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
+            echo "Error: DOCKER_HUB_USERNAME secret is not set!"
+            exit 1
+          fi
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
-          username: ${{secrets.DOCKER_HUB_USERNAME}}
-          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-      - name: Push to Docker Hub
+      - name: Build & Push Docker Image
         uses: docker/build-push-action@v6
         with:
           context: .
           file: Dockerfile
           push: true
-          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-boot-for-beginners:latest
-
+          tags: |
+            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest
+            ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:${{ github.sha }}
